### ISSUE TITLE
[TASK] PostProcessor Plugin

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#1451]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
There is a need for the API of PostProcessor Plugin

**Describe the solution you'd like**
Design the API for PostProcessor Plugin
Initial Design is located at: #972 
PostProcessor Restructure PR #1456 
PostProcessor Plugin API: Version 1: #1458, Version 2: #1466

**Describe alternatives you've considered**

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Postprocessor Inheritance Diagram:
![image](https://user-images.githubusercontent.com/7321071/109328502-bcf94b00-7816-11eb-8528-7efed51db54c.png)

**Comment by wangcj05** [comment]
Interfaced PostProcessor Inheritance Diagram: 
![Uploading image.png…]()

**Comment by wangcj05** [comment]
PostProcessorInterfaceBase Inheritance Diagram:
![image](https://user-images.githubusercontent.com/7321071/109329006-545e9e00-7817-11eb-8fd1-e58212bfaec6.png)

**Comment by wangcj05** [comment]
Models.PostProcessor Inheritance Diagram: 

![image](https://user-images.githubusercontent.com/7321071/109330316-c84d7600-7818-11eb-831b-b9019f277741.png)

**Comment by wangcj05** [comment]
There is no inheritance between framework.Models.PostProcessor and framework.PostProcessors. In addition, there is no inheritance between  framework.PostProcessors and PostProcessorInterfaceBase.

**Comment by wangcj05** [comment]
### Tasks

- Remove PostProcessors/PostProcessor.py base class;
- Create a PostProcessorbase class using Models/PostProcessor.py;
- Create a PostProcessorPluginBase class for plugin;
- All internal post processors should always inherit from PostProcessorbase;
- The base class should be able to provide the formatted data to plugin system (i.e., dict, xarray.Dataset, or pd.DataFrame);
- Plugin should return formatted data (i.e., dict, array.Dataset, or pd.DataFrame) from its run method;

### XML Inputs 

- Current
![image](https://user-images.githubusercontent.com/7321071/109338102-0d76a580-7823-11eb-8a2e-f11c0501ed89.png)

- Under discussion
![image](https://user-images.githubusercontent.com/7321071/109338166-20897580-7823-11eb-8c71-664a14e9f778.png)

**Comment by wangcj05** [comment]
### Plugin API Requirements

- InputData and InputType to process XML inputs
- Data into plugin: dict (other format?)
- Data from plugin: dict (other format?)
- Required method: __initialize__, __localInputAndChecks__, __run__

**Comment by joshua-cogliati-inl** [comment]
I have looked at this and have no objection.  (The implementation may find some additional complications, but it seems reasonable to try.)

**Comment by wangcj05** [comment]
The PostProcessors are restructured in PR #1456, and the proposed PostProcessor plugin API is presented in PR #1458

**Comment by PaulTalbot-INL** [comment]
If I understand correctly, no model implementations are structured to directly inherit from the RAVEN Model entity; rather, each Model "has a" member that is the implementation:
- Code has a Code Interface
- ROM has a supervisedEngine
- ExternalModel has a "sim" or something, the "raven" that get passed down
- Postprocessor has a postprocessor

I'm not sure whether this is our intended future structure or not, but it's fairly notable to make the Postprocessor the first Model entity to depart from this structure.

Would it not make sense to rewrite PostprocessorBase so that it can be extended both in plugins and in RAVEN, and let the Model.Postprocessor "have an" instance of the PostprocessorBase?

Sorry I may be behind on discussion since I missed Monday.

**Comment by wangcj05** [comment]
> If I understand correctly, no model implementations are structured to directly inherit from the RAVEN Model entity; rather, each Model "has a" member that is the implementation:
> 
> * Code has a Code Interface
> * ROM has a supervisedEngine
> * ExternalModel has a "sim" or something, the "raven" that get passed down
> * Postprocessor has a postprocessor
> 
> I'm not sure whether this is our intended future structure or not, but it's fairly notable to make the Postprocessor the first Model entity to depart from this structure.
> 
> Would it not make sense to rewrite PostprocessorBase so that it can be extended both in plugins and in RAVEN, and let the Model.Postprocessor "have an" instance of the PostprocessorBase?
> 
> Sorry I may be behind on discussion since I missed Monday.

@PaulTalbot-INL We have not discussed it yet. The plan is to have a discussion on next Monday morning meeting. Please feel free to comment. I do create two PRs: #1456 and #1458. If you have time, please take a look at these PRs.

**Comment by PaulTalbot-INL** [comment]
For memory and speed, I think it's important that "run" nominally accepts RAVEN DataSets and returns RAVEN DataSets. We might have methods for returning other formats, but I think with the decent API we have maybe this wouldn't be too bad.

An alternative would be to accept xr.Dataset and return xr.Dataset + xml meta, but I think this would generally be less user friendly.

**Comment by wangcj05** [comment]
@PaulTalbot-INL @alfoa @mandd @joshua-cogliati-inl Please check PR #1466 for the new PP plugin API design. Please let me know your comments.

**Comment by PaulTalbot-INL** [comment]
I think a significant discussion is whether to use the `general` and `_localGeneral` structure for naming, or to use polymorphism and extend the methods in the subclasses. I greatly prefer the latter, otherwise as you inherit you get silly things like `_localLocalLocalDoStuff` and it makes a mess of the API.

**Comment by wangcj05** [comment]
### Based on team discussion, the new PostProcessor Plugin API will inherit directly from the PostProcessor Base Class, and we would expose methods from Base Class to API developer.

**Comment by alfoa** [comment]
Closure checklist passed

**Comment by alfoa** [comment]
Closure approved via  #1512
