### ISSUE TITLE
Infrastructure Checklist

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#667]
To increase the trackability of these concerns, we make a checklist here:

- [ ] Assure all developers have access to all test machines
- [x] Construct documentation for starting/restarting CIVET for various users
- [ ] Fix locating the AMSC library on Windows tests
- [ ] Automate the release schedule operations
- [ ] Produce a common library installation script for all operating systems
- [ ] Assure all install procedures load the `raven_libraries` environment before calls to `make`

**Comment by wangcj05** [comment]
@derekstucki Could you give us the current update on these issues?

**Comment by derekstucki** [comment]
It looks like devel and master are tracking exactly as they should.

**Comment by derekstucki** [comment]
I've double checked and all recipes are calling establish_conda_env. As soon as the libs update PR is merged, we should be good to go.

**Comment by derekstucki** [comment]
I've figured out what the problem was with the windows civet only running properly under my user. I'm working with Diego to iron out the solution in a repeatable way.

**Comment by derekstucki** [comment]
The windows civet instructions have been updated to fix the previous problem. I've highlighted in orange the part that Andrea and Paul should go back and do to fix their accounts to be able to run civet. It's currently running under Diego's user and all tests pass on the libs update branch.

**Comment by alfoa** [comment]
@derekstucki update on this issue?

**Comment by derekstucki** [comment]
@alfoa, which issue? It is my understanding that everything is either in a usable/functional state or someone else has started a fix.
