### ISSUE TITLE
ARMA producing nans using the TRAIN_ARMA files in the Hybrid project repository from the September2017 milestone report.

### ISSUE THREAD

**Issue by klfrick2** [idaholab/raven#752]
--------
Issue Description:

Using the raven devel branch and the hybrid project when training the ARMA_W.pk and ARMA_D.pk files the system produces an ARMA_D.pk file that produces nans. But does not complain and issue is not found out until ARMA_D.pk file is used. 

This is accomplished in the hybrid/CashFlowCalcs/2017September/Train_Arma file. 

Data used is the ercotWestDemand_RAVEN.csv, SITE_03247_H.csv files. 

Note: when using the raven devel branch the system will complain until wind is changed to below. 

This is in the HYBRun_trainARMA_1day.xml file.

    <ROM name='demandTXARMA' subType='ARMA'>
      <reseedCopies>False</reseedCopies>
      <Target>Demand,Time</Target>
      <Features>scaling_demand</Features>
      <pivotParameter>Time</pivotParameter>
      <Pmax>6</Pmax>
      <Pmin>6</Pmin>
      <Qmax>1</Qmax>
      <Qmin>1</Qmin>
      <outTruncation>positive</outTruncation>
      <Fourier>31536000,604800,86400,10800</Fourier>
      <FourierOrder>12, 2, 6, 3</FourierOrder> 
    </ROM>
    <ROM name='windARMA' subType='ARMA'>
      <reseedCopies>False</reseedCopies>
      <Target>Speed,Time</Target>
      <Features>scaling_wind</Features>
      <pivotParameter>Time</pivotParameter>
      <Pmax>1</Pmax>
      <Pmin>1</Pmin>
      <Qmax>2</Qmax>
      <Qmin>2</Qmin>
      <outTruncation>positive</outTruncation>
      <Fourier>31536000,604800,43200,3600</Fourier>
      <FourierOrder>1, 1, 1, 1</FourierOrder>   
    </ROM>
  </Models>

--------
##### What did you expect to see happen?

I would expect the ARMA_D.pk file to complain that its outputs produce nans. 

##### What did you see instead?

It let me go ahead and use it. 

##### Do you have a suggested fix for the development team?

Just a simple check. 

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Closing since not valid anymore
