### ISSUE TITLE
IOStep should use the addExpectedMeta to register meta

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#883]
--------
Issue Description
--------
##### What did you expect to see happen?

IOStep should use the addExpectedMeta to register meta

##### What did you see instead?

IOStep can not do that

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@wangcj05 can you explain why? In which case it would need it?

**Comment by PaulTalbot-INL** [comment]
Yes, to note further, the MultiRun and PostProcessor make good use of the "addExpectedMeta" method; with the ROMs printing their own arbitrary variables, it makes sense that the IOStep could use the same "addExpectedMeta" workflow, as well.
